FROM debian:bookworm-slim

ARG MINER_URL
ARG APPSETTINGSFILE

RUN apt-get update
RUN apt-get install -y libicu-dev procps wget
RUN adduser qb
USER qb
WORKDIR /miner
RUN wget $MINER_URL -O ./qli.tar.gz
RUN tar xvzf qli.tar.gz
COPY ${APPSETTINGSFILE} appsettings.json
ENTRYPOINT ./qli-Client
