FROM debian:bookworm-slim

ARG MINER_URL
ARG THREAD_COUNT
ARG LABEL
ARG TOKEN

ENV THREAD_COUNT=$THREAD_COUNT
ENV LABEL=$LABEL
ENV TOKEN=$TOKEN

RUN apt-get update
RUN apt-get install -y libicu-dev procps wget
RUN adduser qb
USER qb
WORKDIR /miner
RUN wget $MINER_URL -O ./rqminer
RUN chmod +x rqminer
ENTRYPOINT ./rqminer --threads $THREAD_COUNT --id $TOKEN --label $LABEL
